name: nfc_counter
description: Example project for my NFC Medium article see https://blog.devowl.de
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geocoder: ^0.2.1
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  maps_toolkit: ^2.0.1
  nfc_manager: ^3.2.0
  oktoast: ^3.3.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/message/
    - assets/json/officers.json
  uses-material-design: true
